# generic distro configuration

##### Yocto Configuration #####
INIT_MANAGER = "systemd"
BBMASK ?= "fake-bbmask-string-that-wont-match-anything"

# locales (which I think are needed for systemd stuff to build right)
GLIBC_GENERATE_LOCALES = "en_US.UTF-8"
IMAGE_LINGUAS = "en-us"

# full-featured vim in packagegroup-core-base-utils
VIRTUAL-RUNTIME_vim = "vim"

NCURSES_ABI_VERSION = "6"

# Disable SPDX SBOM creation. I'm not doing commercial work where that matters.
INHERIT:remove = "create-spdx"

# Don't error on patches which are missing Upstream-Status lines
ERROR_QA:remove = "patch-status"

# This is a hard-coded timestamp applied to parts of the rootfs, but I'd rather use accurate timestamps.
REPRODUCIBLE_TIMESTAMP_ROOTFS = ""

##### Package overrides #####

# I'm pretty sure I don't need systemd-userdbd.service running
PACKAGECONFIG:remove:pn-systemd = "userdb"

# disable jitterentropy random source, it's just a bunch of extra unneeded CPU work
PACKAGECONFIG:remove:pn-rng-tools = "libjitterentropy"

# ensure we support compressed kernel modules (-native recipe must match to make
# the build-time depmod work)
PACKAGECONFIG:append:pn-kmod = " xz zstd"
PACKAGECONFIG:append:pn-kmod-native = " xz zstd"

# Enable the iptables-nft backend
PACKAGECONFIG:append:pn-iptables = " libnftnl"

# Use sshd as a normal service rather than in systemd socket mode
PACKAGECONFIG:remove:pn-openssh = "systemd-sshd-socket-mode"
PACKAGECONFIG:append:pn-openssh = " systemd-sshd-service-mode"

# Don't enable DHCP client daemon
SYSTEMD_AUTO_ENABLE:pn-dhcpcd = "disable"

# ignore the mdns recipe in meta-openembedded
PREFERRED_PROVIDER:libnss-mdns = "avahi-libnss-mdns"
